name: VK-Paints Reusable CI Prod

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      smtp_server:
        required: true
        type: string
      smtp_port:
        required: true
        type: string
      mail_from:
        required: true
        type: string
      publish:
        required: false
        type: boolean
        default: false
      image_tag:
        required: false
        type: string
        default: latest
    secrets:
      SONAR_TOKEN:
        required: true
      SNYK_TOKEN:
        required: true
      SMTP_USERNAME:
        required: true
      SMTP_PASSWORD:
        required: true
      SLACK_WEBHOOK:
        required: true

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Registry Name
        id: registry_case
        run: |
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_OUTPUT
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.registry_case.outputs.OWNER_LC }}/vkpaints-${{ inputs.service_name }}:${{ inputs.image_tag }}
            ghcr.io/${{ steps.registry_case.outputs.OWNER_LC }}/vkpaints-${{ inputs.service_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

